#!/usr/bin/env node
// Gzips web/index.html into firmware/page_html_gz.h as a PROGMEM byte array.
// Forces DEV_MODE to false in the built copy -- the source file keeps it
// `true` so opening web/index.html directly still gives a working local
// preview with mock data.

const fs = require('fs');
const path = require('path');
const zlib = require('zlib');

const SRC = path.join(__dirname, '..', 'web', 'index.html');
const OUT = path.join(__dirname, '..', 'firmware', 'page_html_gz.h');

let html = fs.readFileSync(SRC, 'utf8');
html = html.replace('const DEV_MODE = true;', 'const DEV_MODE = false;');

const gz = zlib.gzipSync(Buffer.from(html, 'utf8'), { level: 9 });

const bytesPerLine = 20;
let body = '';
for (let i = 0; i < gz.length; i += bytesPerLine) {
    const chunk = gz.subarray(i, i + bytesPerLine);
    body += '    ' + Array.from(chunk).map(b => '0x' + b.toString(16).padStart(2, '0')).join(', ') + ',\n';
}

const header = `// Generated by tools/build-page.js from web/index.html -- do not hand-edit.
#pragma once

const uint8_t PAGE_HTML_GZ[] PROGMEM = {
${body}};
const size_t PAGE_HTML_GZ_LEN = ${gz.length};
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, header);

console.log(`Wrote ${OUT} (${html.length} bytes -> ${gz.length} bytes gzipped)`);
